### ISSUE TITLE
Conflict between Epson bluetooth printer and iZettle reader

### ISSUE THREAD

**Issue by mastohhh** [iZettle/sdk-ios#103]
Many of our customers complain about iZettle failing payment when using Epson TM-m30 bluetooth printer.

They must shut down the printer before accepting a payment with iZettle card reader.

Configuration :

- iPad Cellular with a 4G connection
- no wifi network
- our POS with iZettle SDK 1.3.0 and Epson ePOS SDK Ver.2.3.0
- Epson TM-m30 bluetooth printer

Guys from your customer support told me that your iZettle iOS app was compatible with Star bluetooth printers and not Epson ones.

What is your Epson SDK version in your iZettle POS ?
Could you try ePOS SDK Ver.2.3.0 and a Epson Bluetooth printer and tell me if everything's good or not ?

Thanks

**Comment by mattiasjahnke** [comment]
Hi there!

I believe we're using Epsons SDK v2.0.0 (if you can trust their `ePOS2.h` file)

How is it failing a payment? What's happening on the card reader and on the iZettle views? Any error messages, does the card reader shut down?

Updating the Epson SDK on our side could potentially take some time, so we'd like to know more about the problem

**Comment by mastohhh** [comment]
Thank you for your answer.

In iZettle iOS app, did you disable voluntarily Epson's bluetooth printers, or do you let the Epson SDK handle all printers ? I think TM-m30 Epson printer is a new one, but older bluetooth printers should work (for example TM-T88V).

Could you ask your iZettle iOS team (if you're not one of them) to try any Epson Bluetooth printer ?

One of my customer explained me the bug : 

> At cashing, we choose izettle, the amount is displayed, the customer types the code and the circle runs in circles.
> iZettle freezes. After the red smiley indicates an error. When we turn off the bluetooth printer and re-try with the same CB, the payment passes. The card was a Visa. The connection is in 4G. We do not work on Wifi.

I hope this will help you

**Comment by mattiasjahnke** [comment]
Hey,

I don't think we officially support any Epson bluetooth printers in our app today (and not sure if we could find a printer anywhere here in the office to try out).

Anyway, I think it seems pretty unlikely that they would interfere in any way. For all we know, the bug might just as well be that the card payment fails the first time, and succeeds the second time (regardless of Epson printers).

Would be interesting to know what the card reader displays ("Payment cancelled", or is the connection interrupted?).

In order to investigate further on our side, knowing which iZettle customer this is affecting would be of great help. Drop me an email; mattias [[ at ]] izettle [[ dot ]] com and we can take it from there.

**Comment by mastohhh** [comment]
Hi Mattias,

Did you receive my mail ?

Thanks

**Comment by mattiasjahnke** [comment]
Hey, sorry for the delay!

Yes I received it but it got buried in holiday e-mails. I'll continue the investigation tomorrow.

**Comment by mastohhh** [comment]
Thanks. Maybe this can help you : [video](https://www.dropbox.com/s/bhbq9i9gx2jv7lf/bug.izettle-Clip1.mp4?dl=0)

**Comment by mattiasjahnke** [comment]
@mastohhh Thanks for the video.

Are you able to reproduce this on your side (without involving customers)? We're currently working on getting a new version of the SDK out the door and we've fixed a couple of bugs related to the card reader.

If you can reproduce the bug, you could try with the new version to see if the issue is resolved.

**Comment by mastohhh** [comment]
I don't have a cellular iPad and the same iZettle reader to reproduce this bug. But I can create easily a new version an deploy it for this customer. We did this with him to test Espon SDK recently.
