### ISSUE TITLE
'iZettle Cash Register is not compatible with this service' error

### ISSUE THREAD

**Issue by Pivovar63** [iZettle/sdk-ios#135]
Hello,
This is Ilya from Ecwid Customer care team.
Ecwid is an e-commerce solution that can be added to any website or social page. We have an integration with iZettle, you can find more info here https://www.ecwid.com/izettle

We have a customer who faced an issue during the work on iZettle integration. Please, check these screenshots which illustrate the issue:

http://take.ms/X6HbV

'Quote start'
It is actually the izettle app that pops up and shows this message – but I only used and I punshed product in the Ecwid app. The pic shows also a sad face icon.

http://take.ms/zeEPk

See attached print screen picture. This is from their online izettle control panel. It is in Norwegian. 
But translated it says: 
It is not compatible with 3rd partys apps. 
I guess Ecwid is Izettles 3rd party app.
'Quote end'

They can recreate the problem on iPad. Can you please assist on this matter? What can be the cause of the issue?

Just in case, I'd like to clarify how the integration works, in general. A special URL is created automatically after clicking on iZettle button in the Ecwid mobile app (iOS app link https://itunes.apple.com/en/app/ecwid/id626731456?mt=8). We use this URL-Scheme: https://github.com/iZettle/URL-Scheme

Then, iZettle app calls URL that interacts with the Ecwid app. Thus, we have the needed replies: success or error. Depends on the reply either the order is created or the error message is shown (not the one I sent you above).

I hope to hear from you soon. Thank you in advance!

**Comment by mattiasjahnke** [comment]
Hey,

The problem is that the users account is a "cash register" account. That means this account can't be used with third party apps - cash register is a feature in the iZettle POS.

Please note that the URL-scheme is deprecated since over a year ago. This means that the integration could potentially stop working in future versions of the iZettle app. Please upgrade to instead use the iZettle SDK.

**Comment by Pivovar63** [comment]
Thanks for quick answer.
The customer used this case a month ago successfully. Why did this scenario become broken?
And the second question is how can the customer make third party apps working again?

**Comment by mattiasjahnke** [comment]
Hi,

If you are using the URL-scheme, we can't guarantee that it will work properly with new releases of the app, since it's deprecated.

Another explanation could be that the user didn't have the cash register service activated on the account a month ago.

The customer will have to contact our support regarding question about the account.

**Comment by Pivovar63** [comment]
Thank you!
