### ISSUE TITLE
Declined - Card Not Accepted Here

### ISSUE THREAD

**Issue by collymore** [iZettle/sdk-ios#148]
We're seeing this on our iPad app after updating to latest version of SDK.
Card Not accepted here. 
It's not an error we've seen before in the past 18 months but has been reported recently to us lots. 

How can we debug this?
![screen shot 2017-06-23 at 10 04 30](https://user-images.githubusercontent.com/55946/27875543-6d0ea584-61ab-11e7-9ab8-392d2ed74d79.png)

**Comment by arikis** [comment]
Hi @collymore. Most likely, that specific type of card is not supported by the payment processor. How often does this issue occurs and is it always with the same cards? 

It would be great if you could send your iZettle account details (email, name) to `sdk@izettle.com`, so that we can investigate more.
