### ISSUE TITLE
Verifying payments via REST API

### ISSUE THREAD

**Issue by HeyHugo** [iZettle/sdk-ios#153]
Hi,

is it possible to verify/lookup payments made via ios SDK using the iZettle REST API documented here? https://github.com/iZettle/api-documentation

Why I'm asking is because here in the iOS SDK documentation the term `reference` is used for `retrievePaymentInfoForReference `. But in the REST API `purchaseUUID` is used, implying it is a uuid (possibly unknown from `chargeAmount` or `retrievePaymentInfoForReference`)

Same question was asked at repo for REST API documentation https://github.com/iZettle/api-documentation/issues/23

Thanks!

**Comment by mattiasjahnke** [comment]
Hey!

No, the purchase API lists receipts (purchases), while the SDK only deals with payments.

Receipts (purchases) are a part of the iZettle app - where we deal with products, shopping carts, discounts etc.

*We do however automatically create a "purchase" when a payment is made via the SDK, so that the "payment" shows up for the merchant in the iZettle portal (where we list purchases, not payments).*

As you point out, `retrievePaymentInfoForReference` in the SDK provides this query-functionality, but I don't believe we currently have a public REST API for querying the payment status with a `reference`.
