### ISSUE TITLE
Data Harvesting Transparency

### ISSUE THREAD

**Issue by GJNilsen** [iZettle/sdk-ios#156]
Lately some frameworks have been doing a bit more than necessary, like "phoning home" statistics and user data outside of the scope of the framework. For mutual trust, for all parties interacting with this framework, some transparency is needed.

We, for example, do have a really big problem with letting any third party access CoreLocation. Because of our privacy policy, we are on really thin ice if location data is actually shared with iZettle. A complete description on what is collected would be very helpful, so we can be upfront with our clients.

**Comment by arikis** [comment]
Hi @GJNilsen,

iZettle has legal agreements with acquiring banks to geofence merchants to a country they operate in. This means that we should disallow payments made outside of merchants country for various reasons (e.g. taxes).

Hence, we need to use CoreLocation in our SDK. Location data (latitude and longitude) gets retrieved before the payment so that we can decide whether we can continue with it.

We will be preparing a full report on this topic and we'll share it with all SDK partners so that they can communicate it to their users.

**Comment by GJNilsen** [comment]
Thanks. I really appreciate it. After the latest debacle with AccuWeather, its better to be safe than sorry.

**Comment by GJNilsen** [comment]
This issue should not be closed until the report on this topic is published and linked to in the readme document.
