### ISSUE TITLE
NSMicrophoneUsageDescription

### ISSUE THREAD

**Issue by Gerharbo** [iZettle/sdk-ios#178]
Hi,

Apple is failing an uploaded build with the iZettle SDK if you're not including the `NSMicrophoneUsageDescription`. I suppose the SDK required it for older iZettle devices? Is there an anyway to get a version of the SDK without microphone support?

The README should be updated as well.

The message from Apple:
`Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.`

**Comment by arikis** [comment]
Hi @Gerharbo,

`NSMicrophoneUsageDescription` is needed since SDK supports microphone based readers. It very easy to add to your 'Info.plist` file with value of e.g. `The card reader uses the audio jack to connect with your device.`.

After that, you should be able to upload your build successfully. 

I'll update README to include this information.

**Comment by Gerharbo** [comment]
It's indeed very easy to add the `NSMicrophoneUsageDescription`, I will update it.
