### ISSUE TITLE
Crash when reference is to big

### ISSUE THREAD

**Issue by bartoszhernas** [iZettle/sdk-ios#18]
Hey, I just got crash report here with message `Reference exceeded max length (128)`

	Thread : Fatal Exception: iZettleSDKException
	0  CoreFoundation                 0x0000000185acc22c __exceptionPreprocess + 132
	1  libobjc.A.dylib                0x00000001975880e4 objc_exception_throw + 60
	2  InventorumBeta                 0x000000010068c9ec -[iZettleSDK _validateCompletion:] (iZettleSDK.m:278)
	3  InventorumBeta                 0x000000010068cfc4 -[iZettleSDK(Operations) chargeAmount:currency:reference:presentFromViewController:completion:] (iZettleSDK.m:313)
	4  InventorumBeta                 0x000000010015f264 __46-[IZettlePaymentType presentPaymentController]_block_invoke (IZettlePaymentType.m:38)
	5  InventorumBeta                 0x0000000100130258 -[CheckoutViewController paymentTypeChanged:] (CheckoutViewController.m:70)

I think this is too dramatic to crash app, maybe you could strip message in this case and log warning to console?

**Comment by mansbernhardt** [comment]
So you would prefer an NSError back in the completion instead of us throwing an exception? A log would not be enough as the in data is invalid an the call can't proceed, see from the docs below.

- **reference** _(optional)_: The payment reference. Used to identify an iZettle payment, used when retrieving payment information at a later time or performing a refund. Max length 128.

**Comment by bartg** [comment]
`NSError` would be more preferable than a crash. I made a mistake implementing it, but would be much better if user would just see any error instead of crash. Also easier to debug ;)

I think we are misusing it, since we are sending something like `Apple iPhone x 2 - 5,00€; Smasung x 1 - 200,00€;` just because it later appears in iZettle dashboard. (or it was appearing)

I will change it to our basket id, so it wont exceed and we will be able to use it for refunds if we implement them later.

Thank you for help!
