### ISSUE TITLE
iZettle cash register is not compatible

### ISSUE THREAD

**Issue by Repair-Desk** [iZettle/sdk-ios#200]
**Dear Support,**

We're writing our POS register platform integration with iZettle for integrated payment processing. Since our development team is not based in Europe we've shared a test build with one of our customer in Europe however when he login to RepairDesk and proceeds to payment page it display an error "IZettel cash register is not compatible with this service. This account is connected to the cash register. If you want to use that u need to unsubscribe " . 

He was using NOK currency.

i wanted to know why we are facing wrong currency error even we are using "NOK" according to his location as we are sending right currency code . 

Any help will be greatly appreciated.

**Comment by hey-kj** [comment]
I will close this due to inactivity and also that this issue may have occurred in a much older version of the SDK.

The reason this may have happened was because in the previous `chargeAmount` method there was an option to pass in currency, which is a legacy thing and confused integrators. This has been remove for quite a while and should not be an issue anymore.
