### ISSUE TITLE
"i" button is missing for externaldemo account

### ISSUE THREAD

**Issue by oli-gastrofix** [iZettle/sdk-ios#203]
# Expected Behavior

The "i" button to open the info section should be displayed at the upper right corner if one is logging in with UK and NOR accounts.
The issue about the missing "i" button is, that one is not able to log out and re-log in with another account. We always have to uninstall the gastrofix app to log in with another demo account (externaldemode@izettle.com f. e.). If one is logging in with a german account, the "i" is visible

# Current Behavior

The "i" button to open the info section is missing at the upper right corner if one is logging in with externaldemo@izettle.com.

# Steps to Reproduce

Log-in with externaldemo@izettle.com to the current iZettle SDK (v. 1.7.1).

## Context 

Using gastrofix POS and payment provider iZettle with the SDK version 1.7.1.

* Operating Version: iPad Air 2, iOS 11.3.1
* SDK version: 1.7.1 (also 1.6.2)

## Failure Logs

![izettle_i_button](https://user-images.githubusercontent.com/23498826/40656535-0066fa34-6345-11e8-8f02-f011f6ec08a3.jpg)

**Comment by arikis** [comment]
Hey @oli-gastrofix,

The `i` button does not appear here because we are presenting tipping UI. The button is currently only displayed during the transaction. If you want to present the settings view programmatically (to be able to logout and login) you can implement [`presentSettingsFrom:` method](https://github.com/iZettle/sdk-ios#presenting-settings). 

In this case, you could just enter tip amount in the reader, continue to transaction and info button will be displayed in the upper right corner.

We will also investigate adding the button to the tipping view too, but for now you can use custom method to present settings or continue with transaction to be able to tap on info button.

**Comment by oli-gastrofix** [comment]
Thanks @arikis for your fast answer!
