### ISSUE TITLE
Login for one of our customers does not work

### ISSUE THREAD

**Issue by f3lixz** [iZettle/sdk-ios#299]
# Expected Behavior
When putting in login information in this screen:
https://imgur.com/yjJoRth
We're expected to be taken to the devices screen.

# Current Behavior
For one of our customers account the view spins around and takes it back to the login screen (https://imgur.com/yjJoRth) without any error or indication that something went wrong.
When I tried it on one of our accounts it worked as expected
If you do it with a wrong password it correctly displays an error message with an "Incorrect password"-message

# Steps to Reproduce
Open iZettleSDK.shared().presentSettings(from: viewController) and attempt to login. Please message me privately for the specific account that has this problem.

## Context 

* Operating Version: iOS 13
* SDK version:  iZettleSDK.shared().version = 2.3.2

## Failure Logs
Nothing is output neither visually nor in the logs

**Comment by adeemotu** [comment]
@f3lixz could you please share account information

**Comment by nicklasskalleberg** [comment]
![FC895C70-3158-49E0-BC90-9C75B8401B40_1_105_c](https://user-images.githubusercontent.com/68013698/86920046-6628ef00-c129-11ea-8eb8-bda458603bc1.jpeg)
Dan Friis J.Lindeberg admin account. Need more?

**Comment by nicklasskalleberg** [comment]
I just spoke to Martin (partner manager). This might be more support related?

**Comment by adeemotu** [comment]
Thanks, this could help in investigation

**Comment by nicklasskalleberg** [comment]
Is this more support related? 
Could someone at the "2nd line support" contact me to check the account?


Nicklas Enigk Skalleberg
Customer Success Manager 

  

E-mail nicklas.skalleberg@sitoo.com <mailto:nicklas.skalleberg@sitoo.com>
Mobile +46 703 57 03 53 <tel:+46%20703%2057%2003%2053> | Phone +46 8-5000 93 00 <tel:+46%208-5000%2093%2000>
Sitoo AB Regeringsgatan 25, 111 53 Stockholm
Sitoo.com <https://www.sitoo.com/> | Facebook <https://www.facebook.com/sitooab/> | LinkedIn <https://se.linkedin.com/company/sitoo-ab> | Instagram <https://www.instagram.com/sitoo/> | Twitter <https://twitter.com/sitoo>

Disclaimer: This e-mail (including any attachments) is intended only for the recipient(s) named above. It may contain confidential or privileged information and should not be read, copied or otherwise used by any other person. If you are not a named recipient, please contact the sender and delete the e-mail from your system.

**Comment by dmilovanovi** [comment]
Hello again,

Regarding these two accounts please get in contact with our support at: https://www.izettle.com/se/help/contact/options.
We have not identified anything unusual on the SDK side.

On that note, we have released a new version of the SDK v3.0 this week, so please let your development team have a look at https://github.com/iZettle/sdk-ios/releases/tag/3.0.0 

We also have a migration guide should you have any questions around the updating process.

Regards,
Dejan

**Comment by nicklasskalleberg** [comment]
Yes, waiting for answer from your support. There is something with the account that doesn´t make sense.



Nicklas Enigk Skalleberg
Customer Success Manager 

  

E-mail nicklas.skalleberg@sitoo.com <mailto:nicklas.skalleberg@sitoo.com>
Mobile +46 703 57 03 53 <tel:+46%20703%2057%2003%2053> | Phone +46 8-5000 93 00 <tel:+46%208-5000%2093%2000>
Sitoo AB Regeringsgatan 25, 111 53 Stockholm
Sitoo.com <https://www.sitoo.com/> | Facebook <https://www.facebook.com/sitooab/> | LinkedIn <https://se.linkedin.com/company/sitoo-ab> | Instagram <https://www.instagram.com/sitoo/> | Twitter <https://twitter.com/sitoo>

Disclaimer: This e-mail (including any attachments) is intended only for the recipient(s) named above. It may contain confidential or privileged information and should not be read, copied or otherwise used by any other person. If you are not a named recipient, please contact the sender and delete the e-mail from your system.
