### ISSUE TITLE
Processing Event?

### ISSUE THREAD

**Issue by innovationben** [iZettle/sdk-ios#308]
# Expected Behavior

We have custom screen showing when the card payment is being process however this cannot be activated as there seems to be no way to listen for and event trigger that means a payment is currently processing?

# Current Behavior

No processing event type is currently available that we can see?

# Steps to Reproduce

N/A

## Context 

Awaiting a payment, when payment is being processed trigger event within API that shows the payment is being processed. (not using the standard iZettle process screen)

* Operating Version:
* SDK version: 3.0

## Failure Logs

N/A

**Comment by said-iz** [comment]
Hey @innovationben, thanks for the feedback on this! Just so I understand, would you like to be able to know when the payment is being processed through an API or would you also like to be able to present your own UI during the processing step instead of the iZettle SDK one? 

Currently, we don't offer this kind of an API because of all different kinds of things that could happen during the payment which results in a large number of states we need to handle. Due to this complexity, SDK manages this process completely by itself.

**Comment by innovationben** [comment]
Hey Said,

Thanks for the response! Appreciated. 

Essentially the answer is yes. We have our own awaiting payment screen and our own completed payment screen and we have no option to inform the user "we are processing" on our UI. We have "waiting" and "successful/failed" but nothing to inform the user that the payment is being attempted and is it is a unique UI overlaying the iZettle processing screen isn't really an option so we are left a little in limbo with how we feedback to the customer.

I understand that there are lots of failure reasons and things that could go wrong but just knowing the payment is "being attempted" without having to show the standardised iZettle UI would be really really helpful.

**Comment by hey-kj** [comment]
As of now we do not have any plans to implement this feature, but we'll take this in consideration for future developments.
