### ISSUE TITLE
legacy workspace error 

### ISSUE THREAD

**Issue by shoaibhassan21** [iZettle/sdk-ios#309]
i have updated pods and found this error. 

in current version of SDK needs to drag workspace file.  that is against to norm of development for now.

i m using multiple integration in my Repairdesk APP like square , tyro , paypal etc .i have set legacy build system from workspace setting. i can't use work space file in my Xcode project please change the behavior through pods.
these 2 files are mention below. please change the pattern of connectivity. i need to send a release 

iZettleSDK.xcframework
iZettlePayments.xcframework

**Comment by valkovsky** [comment]
Hi @shoaibhassan21,

I've tried to integrate `iZettleSDK` with a simple sample app using `Cocoapods` plus legacy build settings and it worked without any errors (Cocoapods 1.9.3, Xcode 11.6).
I'm not quite sure what is the problem you experience. Could you provide more information about it?

**Note:**
In order to integrate `iZettleSDK 3.0` you need to use cocoapods that supports XCFramework. It is preferable to use the latest cocoapods version - 1.9.3.

**Comment by shoaibhassan21** [comment]
Hey Andrei,

can we have a call.  After updating the izettle version of SDK still facing
the issues  i'm using xcode 12.

regards
shoaib khan

**Comment by hey-kj** [comment]
Hey again, are you still having troubles with integrating our SDK? 

I will close this issue for now due to inactivity but feel free to open again if this is still an issue and we can discuss further.
