### ISSUE TITLE
Reference on bank transaction

### ISSUE THREAD

**Issue by MarcoDeJong** [iZettle/sdk-ios#383]
As a cashier,
I want to see a reference on the bank transaction,
So I can quickly find it in my administration (for refund e.g.)

Context
Whenever a paying customer, returns to the point of sale (e.g. a problem with the product), but they have no ticket of the transaction. Most of the time they will show a bank transaction for proof. However, there is no means to relate the bank transaction to the internal administration. Not by unique IDs, not by reference or whatsoever.

How can I use the SDK to force a description on the bank transaction? Either the unique ticket number generated by Zettle (in the Merchant account), or either by the reference I give by chargeAmount

**Comment by davidzettle** [comment]
Hey Marco, sorry for the long time before reply.

Unfortunately this is not possible, a receipt is required to be able to locate the transaction. This is something that you may have already found out due to our previous conversations in our support service desk but wanted to confirm here so we can close the thread.

Regards,
