### ISSUE TITLE
Card reader to approval with Apple

### ISSUE THREAD

**Issue by kevintq** [iZettle/sdk-ios#409]
We keep getting constantly rejected from Apple, stating we haven't specified D UISupportedExternalAccessoryProtocols and provided a PPID, but the documentation clearly states that you skip that stage tried numerous ways to contact support that would seem to be answering. Is there any way I can possibly get an answer of what we should add to a plist.info to get this approved, we can't be the only one who has this problem

**Comment by tennisgent** [comment]
@kevintq I posted an update describing our same issue getting approval with Apple in this issue: https://github.com/iZettle/sdk-ios/issues/392#issuecomment-1309349583

**Comment by MarcoDeJong** [comment]
I had the same issue and conquered it. I will post my full reply in https://github.com/iZettle/sdk-ios/issues/392

**Comment by davidzettle** [comment]
Hello and thank you for your comments. As stated in: https://github.com/iZettle/sdk-ios/issues/392

We are updating this information in our Portal and help center as this has been required by Apple independently of the reader version as stated above due to our background mode used as well in the Zettle reader 2.

I believe all of you have already had a successful application submitted so I will go ahead and close this thread. If you need to apply for one still you can find the steps here: https://ext-izettle.atlassian.net/servicedesk/customer/portal/3/group/4/create/24 <- to be updated soon to remove only for reader one, so you can just ignore that, download the file and submit after you have filled it and attached it.

Regards,
