### ISSUE TITLE
Feature request: URL scheme triggering of card readers

### ISSUE THREAD

**Issue by Bart-Westenenk** [iZettle/sdk-ios#446]
# Expected Behavior

There is a way for web applications (SPA) to trigger payments in the Zettle application. This works the same on all operating systems.

# Current Behavior

No way currently exists to call both android and IOS from an SPA or web application. SumUp has 1 URL scheme that works for both OSes.

## Context 

We don’t have the capacity to make both an IOS app, Android app and a website for managing our e-commerce application where payments are taken using your Zettle card readers.

* Operating Version: IOS and Android
* SDK version: Irrelevant

**Comment by ppeelen** [comment]
Hi Bart!

Thank you for reaching out. 

In order for me to understand the nature of your question, I would like to ask you what it is you mean with "the Zettle application". Are your referring to the [Zettle Go App](https://apps.apple.com/nl/app/zettle-go-enkelt-kassasystem/id447785763) which can be found on the Apple AppStore as well as Google's Play Store, or are you referring to the Zettle iOS and Android SDK?

If you are referring to the latter, you are very correct in that the current version of the Zettle SDK for iOS does not support SPA. In this case, you would have to integrate the SDK and call the SDK via (e.g. [WKWebView's configuration](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration)) once you wish to start a transaction. You would have to apply a similar strategy for Android.

If your comment was meant as a feature request for the Zettle Go App, then please let me know that this is the case and I will make sure to forward this request to the appropriate team within our organisation.

**Comment by Bart-Westenenk** [comment]
My feature request is meant for the Zettle Go App. My preferred way of this to work is that you can built an url like: zettle://pay?amount=10.00&description=order 202&tx-id=ord-202 and the user gets asked "open with zettle?". The user can then let the customer pay with a zettle card reader (or tap with iphone / other supported payment methods).

**Comment by ppeelen** [comment]
Thank you for confirming that. I have forwarded your request to the appropriate team which will look into this. 

Unfortunately, since this repository if regarding the Zettle iOS SDK, there will not be an update regarding this feature request here. I would like to suggest you contact our support via the "support" button on the top right corner of https://developer.zettle.com, or last option in the menu of said site if you are on a mobile device. Our support desk might be able to inform you if such a feature is selected for development. Therefore I will close this request.

You could refer to this thread in the support ticket.

Again, thank you for reaching out.
