### ISSUE TITLE
Cannot login in-app, 403 JSON response in web view

### ISSUE THREAD

**Issue by vladdeSV** [iZettle/sdk-ios#448]
# Expected Behavior

I expect to be able to log in to the Zettle web-view.

# Current Behavior

When I submit my login credentials, I get shown a JSON response:

```json
{"code":403,"message":"HTTP 403 Forbidden"}
```

However, if I open that forbidden page in Safari directly, the page works perfectly.

https://github.com/iZettle/sdk-ios/assets/7542961/1028def5-8fd2-43ab-bb41-cae89a3d8dd1

# Steps to Reproduce

I do not know if there is anything specific other than to open the login window for Zettle.

## Context 

I've gotten the same error when logging into a test account and a production account. The code for initiating the SDK has been the same since a couple a months ago, and I could log in back then. In-app the website is displayed in Swedish (my language), but when I open it with Safari the page is in English.

* Operating Version: iOS 17.2.0
* SDK version: 3.18.0

## Failure Logs

N/A

**Comment by MBelogorodtsev-IZ** [comment]
Hello @vladdeSV,
Thank you for reaching out!

Could you please verify that nothing has changed on the developer portal for the app you're using? 
Especially make sure that the bundle id is not shared with any other applications and the redirect url has been set up correctly.

**Comment by MBelogorodtsev-IZ** [comment]
Thank you for screenshot and detailed information!
I have looked through all of it and I can see nothing wrong with your iOS integration.
I will contact the team owning the login flow and come back to you!

Could you please double check also that there is no other app created in Zettle developer portal that use the `se.savea.booking.v3` bundle id? Maybe even on the other Zettle developer account. Because this also could be the possible reason for the behaviour you're experiencing.
Thank you in advance!

**Comment by vladdeSV** [comment]
I checked, and we have only one app in the Zettle developer portal with that bundle id. I am very certain we only have one Zettle developer account, mine. Although I think it's very unlikely, but could someone else have registered a Zettle app with our bundle id?

Thank you for the help so far, and for confirming that our integration in the app seems well :)

**Comment by MBelogorodtsev-IZ** [comment]
Hello @vladdeSV, 

> could someone else have registered a Zettle app with our bundle id?
It's highly unlikely I would say.

I got a response from our support team to ask you to create a ticket in the [Service desk support portal](https://ext-izettle.atlassian.net/servicedesk/customer/portal/3). They will gather the detailed information about the issue and will escalate it to the specific team so that your issue will be solved as soon as possible. 

Sorry that I'm not able to help right here from the SDK developer's perspective but I'm more than sure that the support will help you :)  
Closing this issue for now.
