### ISSUE TITLE
Developping against iZettle

### ISSUE THREAD

**Issue by groue** [iZettle/sdk-ios#54]
Hello,

I'm starting the integration of iZettle in an application. I have an API key.

How can I develop against your SDK and test all scenarios without performing any real transactions?

Thanks in advance

**Comment by mattiasjahnke** [comment]
Hey @groue 

We don't offer a test environment for the SDK (since that would involve using non-production card readers and cards). If you've received credentials to a demo account, that account will automatically revert all transactions made through it. If you have another account you could revert the transaction either through the web portal, the SDK (using the refund method) or the iZettle app.

Hope that answers your question

**Comment by groue** [comment]
Thanks for your anwser. I'm a contractor, and my client eventually gave me the password for the demo account externaldemo@izettle.com, after I have opened this issue. And he told me as well about this refund policy.

If I had a suggestion to you: make this information easy to find, with clear words, calling a spade a spade (including everything relative to externaldemo@izettle.com, which is nowhere to be found on the internet, for no good reason I can think of). For contractors, your SDK can be quite opaque right now.

It the same vein: https://www.izettle.com/gb/help/articles/1084714-connecting-a-card-reader-pro-via-bluetooth is much too much hard to find, when you just want to pair a card reader and start your tests.

Have a nice day, and thank you for your nice SDK. It is a breeze to use (as soon as one has all the information he needs) :-)
