### ISSUE TITLE
Module not found – newbie alert

### ISSUE THREAD

**Issue by shankiesan** [iZettle/sdk-ios#90]
First off – I'm pretty inexperienced with iOS development (I'm a JS developer trying to integrate iZettle into a React Native app). I've successfully integrated Cocoapods with React Native before, but I'm  stuck at the start of this one!

Whenever I add `@import iZettleSDK; ` to the `.m` file of my Cocoatouchclass, xcode tells me `Module iZettleSDK not found`. 

I've tried a bunch of the other 'module not found' explanations around SO and like (adding to linked frameworks, embedded binaries etc) but to no avail.

Can anyone help this Obj-C newb?

**Comment by shankiesan** [comment]
Wow! That must be a record time from posting an issue to finding a solution to my own problem.

I tried re-installing my pod and got the error:

```
[!] The `MyProject [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-MyProject/Pods-MyProject.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

In the end, all I had to do was remove the Framework Search Paths defined in Build Settings – it looks like then it uses the settings built into the pod.

😃

**Comment by AlexKvazos** [comment]
@shankie-san Hey man, did you mange to create a react-native api for this sdk? Are you making it open source? Regards.

**Comment by shankie-san** [comment]
Hey @AlexKvazos I haven't explicitly made a big deal of the project because the code isn't really production-ready, but it does work. If you want to fork it and dissect it yourself, feel free – it's available [https://github.com/shankie-san/cbc-payments](https://github.com/shankie-san/cbc-payments) . If you need a hand with any of it, give me a shout – though obviously I'm not an iOS dev, so I'll have limited input on the Swift/ObjC bit!
